apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-homepage-tls
  namespace: my-homepage
spec:
  secretName: my-homepage-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - homepage.romaine.life
