apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: my-homepage
resources:
- serviceaccount.yaml
- deployment.yaml
- service.yaml
- certificate.yaml
- xlistenerset.yaml
- httproute.yaml
images:
- name: romainecr.azurecr.io/my-homepage
  newName: romainecr.azurecr.io/my-homepage
  newTag: a86e574
